### ISSUE TITLE
Support for Fiddle (instead of FFI)?

### ISSUE THREAD

**Issue by DaKaZ** [gdelugre/ruby-nfqueue#2]
Hello,

I was going to try out this library today (in addition to the nfnetlink ruby library) but the embedded environment I am working in does not have FFI support but it does have support for Fiddle.  I am not well versed in FFI vs Fiddle, but they seem to be very similar and since Fiddle is part of the core Ruby standard library, it seems like that would be good to support it.  Is there any chance you would consider porting to Fiddle?

**Comment by gdelugre** [comment]
I didn't know there was a replacement for FFI directly integrated into Ruby.

If this is working consistently across different versions of MRI, I would be up to get rid of that dependency and use Fiddle instead.

**Comment by DaKaZ** [comment]
Well... I got FFI ported to our OpenWRT environment.  So... lets not waste effort here.  For those interested the repository is here: https://github.com/DaKaZ/ruby-openwrt
